POST http://localhost:3000/category/create HTTP/1.1
content-type: application/json

{
    "title": "Camisetas sem Estampa",
    "discription": "Camiseta basica das basicas",
    "image": "https://i.imgur.com/iBeOKdt.jpeg"
    
}

###

GET http://localhost:3000/category/create HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/category//read/2 HTTP/1.1
content-type: application/json

###
PUT http://localhost:3000/category/show/2 HTTP/1.1
content-type: application/json

{
    "title": "Camisetas sem Estampa",
    "discription": "Camiseta basica das basicas",
    "image": "https://i.imgur.com/iBeOKdt.jpeg"
    
}

###
DELETE http://localhost:3000/category/delete/2 HTTP/1.1
content-type: application/json


