POST http://localhost:3000/camisa/create HTTP/1.1
content-type: application/json

{
    "tamanho": "tamanho M",
    "material": "Algodão 100%", 
    "cor": "Azul Escuro"
}

###

GET http://localhost:3000/camisa/read HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/camisa/show/2 HTTP/1.1
content-type: application/json


###
PUT http://localhost:3000/camisa/update/1 HTTP/1.1
content-type: application/json

{
    "tamanho": "tamanho P",
    "material": "Algodão 100%", 
    "cor": "Azul Escuro"
}

###

DELETE  http://localhost:3000/camisa/delete/1 HTTP/1.1
content-type: application/json